version: '2'

services:
  redis:
    # name: "redis"
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - net-bull
  
  arena:
    image: 'marshalw/arena'
    volumes: 
      - ./config/arena.json:/opt/arena/src/server/config/index.json
    ports:
      - '4567:4567'
    networks:
      - net-bull

networks: 
  net-bull: